#  ___    _       _____
# | __|__| |_  __|_   _| _ __ _ __ ___
# | _|/ _| ' \/ _ \| || '_/ _` / _/ -_)
# |___\__|_||_\___/|_||_| \__,_\__\___|
#   EchoTrace v${project.version}, Minecraft 1.21+

# Reload in game with /echotrace reload

# Set a prefix to be prepended to all plugin messages
# Can use MiniMessage and Legacy message formatting
prefix: "&8&l[&3&lEchoTrace&8&l] &r"

# Set a language file to use from plugins/EchoTrace/language
# You may define your own and set it here without the '.yml'
language: en

# EchoTrace always checks for updates once on startup
# A check is then carried out at the specified interval
# [hours] When set to 0, no further checks are scheduled
update-check-interval: 12

# Whether to only check for full releases, or for any version
# When set to false, EchoTrace also notifies you, when a new
# prerelease or development version is available on Modrinth
releases-only: true

# Command cooldowns for commands that create new traces to
# prevent players from spamming them to cause lag (in ms)
command-cooldowns:
  # /trace position [...]
  position: 2500
  # /trace entity [...]
  entity: 2500
  # /trace player [...]
  player: 2500
  # /trace block [...]
  block: 5000
# Bypassed by operators and players with the
# echotrace.bypass.cooldowns permission node

# Whether only the player executing the command should
# be able to see and hear the summoned echo trace
client-side: true

# How close must a player be to a location in order
# for it to be rendered with particles? (in blocks)
render-distance: 64

# How many render requests should the trace renderer
# render each tick? Unhandled requests are delayed
# and will be rendered when the capacity is there
render-cap: 1024

# When scanning an area for blocks to trace, we do
# it in batches to avoid overloading your server.
# How many blocks should we check each tick?
batch-size: 1024

# We pause all traces if your server is below
# the specified TPS threshold to reduce load
min-tps: 19.5

# Settings related to an ongoing trace
tracing:

  # Particle to spawn (disable with count 0)
  particle:
    type: SOUL_FIRE_FLAME
    speed: 0.0
    count: 1

  # Sound to play (disable with volume 0)
  sound:
    type: BLOCK_SCULK_CATALYST_BLOOM
    volume: 0.75
    pitch: 0.5

  # How far to step forward each time
  # (always keep this value positive)
  step-size: 0.5

  # How many game ticks to wait,
  # before continuing the trace
  interval: 1

  # How many points to
  # draw each interval
  count: 1

# Traces hitting the targeted player
on-hit:

  # Particle to spawn (disable with count 0)
  particle:
    type: SOUL_FIRE_FLAME
    speed: 0.25
    count: 10

  # Sound to play (disable with volume 0)
  sound:
    type: BLOCK_SCULK_SHRIEKER_BREAK
    volume: 0.75
    pitch: 0.25

# What should be the maximum allowed
# search radius for block targets?
# (requires a server restart)
max-radius: 100

# How big of an area should we scan
# when no radius has been provided?
default-radius: 25

# How many points to draw when
# no count has been provided
default-points: -1

# How many degrees to turn towards
# the right direction each run
turn-rate: 10.0